<?php

/**
 * @file
 * Install/uninstall tasks for the Salesforce Pull module.
 */

/**
 * Implements hook_install().
 */
function salesforce_pull_install() {
  variable_set('salesforce_pull_limit', 50);
}

/**
 * Implements hook_uninstall().
 */
function salesforce_pull_uninstall() {
  // Remove salesforce_pull_data_{object_type} variables
  foreach (salesforce_mapping_get_mapped_objects() as $types) {
    variable_del('salesforce_pull_data_' . $types);
  }
}

