<?php

/*
 * Implements hook_cron()
 */
function salesforce_pull_cron() {
  salesforce_pull_get_updated_records();
  salesforce_pull_process_records();
}

/*
 * Pull updated records and place them in the queue
 */
function salesforce_pull_get_updated_records() {
  $sfapi = salesforce_get_api();
  // @todo: Create filter for SOQL query
  $sfapi->query();
}

/*
 * Process records in the queue
 */
function salesforce_pull_process_records() {
  // @ todo: get Salesforce object data and update drupal entity
  $sfapi->query();
}