<?php

/*
 * Implements hook_cron()
 */
function salesforce_pull_cron() {
  salesforce_pull_get_updated_records();
  salesforce_pull_process_records();
}

/*
 * Pull updated records and place them in the queue
 */
function salesforce_pull_get_updated_records() {

  $sfapi = salesforce_get_api();

  //@todo get timestamp
  foreach (salesforce_mapping_get_mapped_objects() as $types) {
    $results = $sfapi->query('SELECT+id+from+' . $types); // . '+where+LastModifiedDate>2012-09-15T17:04:47Z'
    $settings = array(
      'timestamp' => time(),
    );
    variable_set('salesforce_pull_data_' . $types, $settings);
  }


  return '';
}

/*
 * Process records in the queue
 */
function salesforce_pull_process_records() {

  $sfapi = salesforce_get_api();
  //@todo process queue
  dpm($sfapi->apiCall('sobjects/Organization/00DE0000000dORNMA2'));

  return '';
}
